global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: "appointment-management"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["appointment-management-da90d3c8d8ca.herokuapp.com"]

remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: "1732643"
      password: "__GRAFANA_API_TOKEN__"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

