global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "appointment-management"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["appointment-management-da90d3c8d8ca.herokuapp.com"]

remote_write:
  - url: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-cb60e464-7a85-46fb-9797-e331c2d55611/api/v1/remote_write
    sigv4:
      region: us-east-2
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
