global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'appointment-management'
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['appointment-management-da90d3c8d8ca.herokuapp.com']

remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: '1732643'
      password: '${GRAFANA_API_TOKEN}'
