global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'appointment-management'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['https://appointment-management-da90d3c8d8ca.herokuapp.com']

remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    authorization:
      credentials: '${GRAFANA_API_TOKEN}'

