global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'appointment-management'
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '54.159.116.102:80'
          - '18.208.60.216:80'
          - '52.5.82.174:80'
          - '54.165.58.209:80'


remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: '1732643'
      password: '${GRAFANA_API_TOKEN}'
