name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install

      - name: Push metrics to Prometheus
        env:
          GRAFANA_API_TOKEN: ${{ secrets.GRAFANA_API_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer $GRAFANA_API_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{"some_metric": 1}' \
               https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push

      # Optional: Deploy steps can be added here
