name: Test Prometheus Query

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: echo "GRAFANA_API_TOKEN=$GRAFANA_API_TOKEN" >> $GITHUB_ENV

      - name: Test Prometheus API Query
        run: |
          curl -G 'https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/api/v1/query' \
            -H "Authorization: Bearer $GRAFANA_API_TOKEN" \
            --data-urlencode 'query=up'
