name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Fetch GRAFANA_API_TOKEN from GitHub Secrets
        run: echo "GRAFANA_API_TOKEN=${{ secrets.GRAFANA_API_TOKEN }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Heroku
        run: git push heroku main

      - name: Configure Prometheus Push
        run: |
          echo "remote_write:
            - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
              basic_auth:
                username: '1731691'
                password: '${{ secrets.GRAFANA_API_TOKEN }}'" > prometheus.yml

      - name: Deploy Prometheus
        run: mvn spring-boot:run
